### ISSUE TITLE
Padding may be off

### ISSUE THREAD

**Issue by Byteron** [Doraku/Ecs.CSharp.Benchmark#12]
I'm not sure of your intend of course, but if I understood correctly the padding is supposed to add additional entities between those entiies who are iterated.
so a 100_000 entities run with a padding of ten 10 should spawn 1_100_000 entities of which 100_000 are iterated, correct?

because if so then I think the padding is off. It seems the padding entities also have the `C1/C2/C3` components, resulting in them being iterated as well, right?
I remember a while back that there was Padding1 etc components for that, though that has changed since then.
was that intentional?

**Comment by Byteron** [comment]
nevermind I'm dumb.

**Comment by Doraku** [comment]
Normally the entities used for padding does not have the full composition expected by the system so they should not be iterated. They also reuse the components used by the system to actually have an impact on the component stores. If we were padding with completely different component types, it wouldn't impact the same way the storage of the libraries (depending of their implementation). The goal is just to give a more realistic performance assessment of the libraries in real conditions where entities are not happily stored one after an other with their component nicely packed :) (at least for non archetype implementations).

**Comment by Byteron** [comment]
Yeah, I realised this shortly after I had posted the issue. Thanks confirming!
