### ISSUE TITLE
Add C/C++ ecs benchmarks for reference

### ISSUE THREAD

**Issue by kiririn39** [Doraku/Ecs.CSharp.Benchmark#13]
why, not? Just to make people aware of alternatives, and to give a glimpse of them. Also some of them have ports or bindings to sharp so I guess it's relatable. And, no, I'm not trying to convince anyone to use one over the other 
Here one I've found https://github.com/abeimler/ecs_benchmark

**Comment by Doraku** [comment]
Sure why not, as long as it's simple to integrate with the others :) (and I'm not the one doing it haha)
