### ISSUE TITLE
Are Pull requests still integrated?

### ISSUE THREAD

**Issue by friflo** [Doraku/Ecs.CSharp.Benchmark#14]
Hi,

I would like to add another ECS library.
see: https://github.com/friflo/Friflo.Json.Fliox/tree/main/Engine

I see: https://github.com/Doraku/Ecs.CSharp.Benchmark/pull/11 is still open.

Are new ECS libraries integrated in this benchmark?

**Comment by Doraku** [comment]
Hey, I've been on a hiatus for some times but I'm slowly getting back into my projects :) It should be back to life by next week.
