### ISSUE TITLE
Benchmark fails to run since changing TargetFramework to: net8.0-windows

### ISSUE THREAD

**Issue by friflo** [Doraku/Ecs.CSharp.Benchmark#15]
With `<TargetFramework>net7.0-windows</TargetFramework>` it was fine - I tried it today.
I was integrating nuget: Friflo.Engine.ECS.

This change in the *.csproj file now throws the error dumped below.
`<TargetFramework>net8.0-windows</TargetFramework>`

If I change to `<TargetFramework>net8.0</TargetFramework>` it runs.
But I have to remove MonoGame from benchmark because it is not compatible with net8.0.

I guess the suffix `-windows` prevents running on Linux & macOS. Not sure.
Would be nice if tests can run also on these platforms.

Error:
```
dotnet run -c Release --filter *HypEcs*
// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 17 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet  restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in G:\_dev\ECS\Doraku-Ecs.CSharp.Benchmark\source\Ecs.CSharp.Benchmark\bin\Release\net8.0-windows\6b12e65d-f600-4641-9739-7a9ac928b996
// command took 1.18s and exited with 1
// ***** Done, took 00:00:01 (1.26 sec)   *****
// Found 1 benchmarks:
//   CreateEntityWithOneComponent.HypEcs: Job-HNUWYM(InvocationCount=1, UnrollFactor=1) [EntityCount=100000]

Setup power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: High performance)
// Build Error: Standard output:

 Standard error:
   Determining projects to restore...
G:\_dev\ECS\Doraku-Ecs.CSharp.Benchmark\source\Ecs.CSharp.Benchmark\bin\Release\net8.0-windows\6b12e65d-f600-4641-9739-7a9ac928b996\BenchmarkDotNet.Autogenerated.csproj : error NU1201: Project Ecs.CSharp.Benchmark is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Project Ecs.CSharp.Benchmark supports: net8.0-windows7.0 (.NETCoreApp,Version=v8.0)
  Failed to restore G:\_dev\ECS\Doraku-Ecs.CSharp.Benchmark\source\Ecs.CSharp.Benchmark\bin\Release\net8.0-windows\6b12e65d-f600-4641-9739-7a9ac928b996\BenchmarkDotNet.Autogenerated.csproj (in 97 ms).
  1 of 2 projects are up-to-date for restore.

// BenchmarkDotNet has failed to build the auto-generated boilerplate code.
// It can be found in G:\_dev\ECS\Doraku-Ecs.CSharp.Benchmark\source\Ecs.CSharp.Benchmark\bin\Release\net8.0-windows\6b12e65d-f600-4641-9739-7a9ac928b996
// Please follow the troubleshooting guide: https://benchmarkdotnet.org/articles/guides/troubleshooting.html
```

**Comment by friflo** [comment]
Additional note:

I tried the latest version without my changes.
https://github.com/Doraku/Ecs.CSharp.Benchmark/commit/70c0f5482e913dc7c0bc518dca9a270062f55123

**Comment by Doraku** [comment]
there was an other error during initialisation with the Morpeh context at runtime which was not picked up by the ci for some reason :/ not sure if this was linked.

I also changed the monogame dependencies so it should be compatible with more os.

Currently trying to rerun everything on my potato computer to update readme and results.

**Comment by friflo** [comment]
> I also changed the monogame dependencies so it should be compatible with more os.

I tried following revision now successful
https://github.com/Doraku/Ecs.CSharp.Benchmark/commit/3574b2dfb948e941a208f77eaf9e94b73d58e6bf

So with all your csproj changes.
Thx for fast response!
