### ISSUE TITLE
Error running benchmark: `Must be elevated (Admin) to use ETW Kernel Session (required for Hardware Counters and EtwProfiler).`

### ISSUE THREAD

**Issue by friflo** [Doraku/Ecs.CSharp.Benchmark#17]
Hi,

I wanted to run all benchmarks on my system today.
I get the error shown below.

It is related the change (add) in the *.csproj file.
```xml
  <DefineConstants>CHECK_CACHE_MISSES</DefineConstants>
```

I guess the tests should run without admin rights to avoid confusion.
Ulli

Error:
```
>dotnet run -c Release
// Validating benchmarks:
//    * Must be elevated (Admin) to use ETW Kernel Session (required for Hardware Counters and EtwProfiler).
```

**Comment by Doraku** [comment]
ah commiting this was an error I usually leave it commented as as you said it needs admin right to execute this counter. I just change it locally when generating the benchmark results to have more infos, I'll change the way it works to not do that mistake again.

**Comment by friflo** [comment]
Thx!

Only for the records.
The benchmark did also run successful on: Mac Mini M2 (ARM)
