### ISSUE TITLE
Add "Arch" ECS ? 

### ISSUE THREAD

**Issue by genaray** [Doraku/Ecs.CSharp.Benchmark#2]
I recently wrote my own ECS which is archetype based : https://github.com/genaray/Arch
Its still under development but already useable. However it will be a bit different than Default.ECS, it will e.g. not include a mechanic for systems. Instead its intention is to stay minimal and let the user build the world around it. 

What exactly are the conditions for new ECS libs being listed and benchmarked here ? SInce at some point i would like seeing it in here.

**Comment by Doraku** [comment]
Hey, I am going to quote the readme :D
> This repo contains benchmarks of some c# ECS frameworks. Feel free to add your own or correct usage of existing ones! Please make you framework available as a nuget package to ease referencing and updating versions.

I can see that your lib is not available as a nuget but it didn't stop me to add other ecs libraries anyway. The code of the benchmark is minimal, the logic is to create a `BaseContext` which initialize what is needed for all tests (the world for example) and then in each benchmark type you do your thing.
I can see also that you only support net6/net7, I should  update the benchmark to run on net6 it wasn't officially out the last time I worked on this >_<

**Comment by genaray** [comment]
Thanks for your fast answer ! :D 
Oh... i totally overlooked, sorry ^^ But good to know, i think i'll add my code samples to the benchmark in a few days once i have a clean version set up and the first nugget package. Unfortunately i cant go much lower with the net version since i heavily use some of the new features. But i will look what is possible :)

**Comment by Doraku** [comment]
it's probably best to up the benchmark version anyway, especially when net7 releasing this November they made a lot of internal optimization which may impact the result :)

**Comment by Doraku** [comment]
I cleaned up the project a little and moved it to net6, feel free to ask if you have issue integrating your framework in there once it's ready :)

**Comment by Doraku** [comment]
added results, good job :) I think I should add more test that are closer to real usage. Currently since Arch is archetype based and the benchmark has only one entity composition, it probably give it the advantage. The padding scenario was supposed to simulate something closer to reality where your entities might not be the only one. Maybe I should add a scenario with multiple entity composition (and so multiple archetype) to see how it fares :)

**Comment by genaray** [comment]
> added results, good job :) I think I should add more test that are closer to real usage. Currently since Arch is archetype based and the benchmark has only one entity composition, it probably give it the advantage. The padding scenario was supposed to simulate something closer to reality where your entities might not be the only one. Maybe I should add a scenario with multiple entity composition (and so multiple archetype) to see how it fares :)

Thanks a lot ! :) And glad to see that it performs actually pretty good, feels kinda nice. 

But i totally agree, the current benchmark lacks a few real usage scenarios which could change the results. I also think that Arch will be slower with multiple archetypes, however it will probably compensate this by utilizing the cache more. Furthermore it still lacks a few features which could also have an performance impact ^^
