### ISSUE TITLE
Update README Results

### ISSUE THREAD

**Issue by xentripetal** [Doraku/Ecs.CSharp.Benchmark#30]
New libraries have been added over time and they aren't reflected in the README. Would be nice to have a refreshed run and comparison of all the different benchmarks.

**Comment by Doraku** [comment]
yeah sorry I've been reporting doing this forever now >_< I'll try to get on with it.

**Comment by xentripetal** [comment]
I started a full run this morning before seeing this. Feel free to close my mr and do your own, but posted #35 with my run results.

Takes like 5 hours to do a full run, its wild

**Comment by xentripetal** [comment]
Also interestingly I've never ran the tests on my x86 desktop before this. On my M1 macbook TinyECS wins by a landslide but not here.

**Comment by Doraku** [comment]
> Takes like 5 hours to do a full run, its wild

yeah that's why I've dodge it for so long >_> there's probably some optimization to do (for exemple every context are initialized for each tests even when not used), there's probably something to do here. Or maybe change the parameters to accept less stable results (probably the worst solution).

**Comment by Doraku** [comment]
wow looking at the result `Morpeh` systems are taking forever! This is almost Entitas level of slow :o
